"""payments 增加 provider_trade_no（渠道交易号，对账用）

Revision ID: 0b32dc82b02c
Revises: a923bce901ba
Create Date: 2026-10-04 01:47:21.246408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b32dc82b02c'
down_revision: Union[str, Sequence[str], None] = 'a923bce901ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_trade_no', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_provider_trade_no'), ['provider_trade_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_trade_no'))
        batch_op.drop_column('provider_trade_no')

    # ### end Alembic commands ###
